---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs-internal
  namespace: rustfs
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rustfs.local.timmybtech.com`)
      kind: Rule
      services:
        - name: rustfs-svc
          port: 9001
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs-endpoint-internal
  namespace: rustfs
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rustfs-endpoint.local.timmybtech.com`)
      kind: Rule
      services:
        - name: rustfs-svc
          port: 9000
  tls:
    secretName: local-timmybtech-com-tls
