---
apiVersion: v1
kind: Namespace
metadata:
  name: vikunja
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files-pvc
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-synologynas
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-env
  namespace: vikunja
data:
  VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.local.timmybtech.com"
  VIKUNJA_DATABASE_HOST: "<path:secret/data/database#PG_HOST>"
  VIKUNJA_DATABASE_PASSWORD: "<path:secret/data/database#PG_PASSWORD>"
  VIKUNJA_DATABASE_TYPE: "postgres"
  VIKUNJA_DATABASE_USER: "<path:secret/data/database#PG_USER>"
  VIKUNJA_DATABASE_DATABASE: "vikunja"
  VIKUNJA_SERVICE_JWTSECRET: "<path:secret/data/argocd#VIKUNJA_SERVICE_JWTSECRET>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
        app.kubernetes.io/name: vikunja
    spec:
      containers:
        - name: vikunja
          image: vikunja/vikunja:2.1.0
          ports:
            - containerPort: 3456
          envFrom:
            - configMapRef:
                name: vikunja-env
          volumeMounts:
            - name: files
              mountPath: /app/vikunja/files
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: vikunja-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja
  namespace: vikunja
spec:
  selector:
    app: vikunja
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3456
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja-internal
  namespace: vikunja
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vikunja.local.timmybtech.com`)
      kind: Rule
      services:
        - name: vikunja
          port: 80
  tls:
    secretName: local-timmybtech-com-tls
