---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: openfaas
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  basic-auth-user: <path:secret/data/argocd#OPENFAAS_USER>
  basic-auth-password: <path:secret/data/argocd#OPENFAAS_PASSWORD>
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-internal
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfaas.local.timmybtech.com`)
      kind: Rule
      services:
        - name: openfaas
          port: 80
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-public
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfaas.timmybtech.com`)
      kind: Rule
      services:
        - name: openfaas
          port: 80
  tls:
    secretName: timmybtech-com-tls
