---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-internal
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfaas.local.timmybtech.com`)
      kind: Rule
      services:
        - name: openfaas
          port: 80
  tls:
    secretName: local-timmybtech-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-public
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openfaas.timmybtech.com`)
      kind: Rule
      services:
        - name: openfaas
          port: 80
  tls:
    secretName: timmybtech-com-tls
